#!/usr/bin/env node
/**
 * Post-build script to generate index.html with correct asset references
 * This runs after SWC/esbuild builds the assets
 * NOTE: This script is deprecated - index.html is now generated by turbopack-build.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const distPath = path.join(__dirname, '..', 'dist');
const assetsPath = path.join(distPath, 'assets');

// Find the main entry JS file (largest index*.js file)
function findEntryFile() {
  if (!fs.existsSync(assetsPath)) {
    console.error('❌ Assets folder not found');
    process.exit(1);
  }

  const files = fs.readdirSync(assetsPath);
  const jsFiles = files
    .filter(f => f.startsWith('index') && f.endsWith('.js'))
    .map(f => {
      const filePath = path.join(assetsPath, f);
      const stats = fs.statSync(filePath);
      return { name: f, size: stats.size };
    })
    .sort((a, b) => b.size - a.size); // Sort by size, largest first

  if (jsFiles.length === 0) {
    console.error('❌ No index*.js files found');
    process.exit(1);
  }

  // The entry file is usually the largest
  return jsFiles[0].name;
}

// Find CSS files
function findCssFiles() {
  if (!fs.existsSync(assetsPath)) {
    return [];
  }

  const files = fs.readdirSync(assetsPath);
  return files.filter(f => f.endsWith('.css'));
}

// Generate index.html
function generateIndexHtml() {
  const entryFile = findEntryFile();
  const cssFiles = findCssFiles();

  console.log(`📦 Found entry file: ${entryFile}`);
  if (cssFiles.length > 0) {
    console.log(`📦 Found ${cssFiles.length} CSS file(s)`);
  }

  const cssLinks = cssFiles
    .map(css => `    <link rel="stylesheet" href="/assets/${css}">`)
    .join('\n');

  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
${cssLinks}
    <title>WMS - Warehouse Management System</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/assets/${entryFile}"></script>
  </body>
</html>
`;

  const indexPath = path.join(distPath, 'index.html');
  fs.writeFileSync(indexPath, html, 'utf8');
  console.log('✅ Generated index.html');
}

// Run
try {
  generateIndexHtml();
} catch (error) {
  console.error('❌ Error generating index.html:', error);
  process.exit(1);
}

